/**
 * Parallel HBC project generator.
 *
 * spine -> fan-out -> assemble:
 *   1. One fast spine call pins every cross-section fact (see spine.ts).
 *   2. Each section unit is generated by its own CONCURRENT model call, bounded
 *      by a small pool, so wall-clock time collapses to the slowest unit
 *      (~25-45s) instead of one 3-5 minute sequential stream.
 *   3. Units are stitched together in order under the H1 title. The old
 *      whole-document "expansion pass" is gone — per-unit word targets plus a
 *      cheap per-unit top-up keep the length on target.
 */

import { projectAgent } from "../agents/project.agent";
import { PROJECT_VOICE, PROJECT_VOICE_ALEVEL } from "../projectVoice";
import { withRetry } from "../retry";
import { buildSectionUnits, isALevel, type SectionUnit } from "./sections";
import { generateSpine, renderSpineContext, type ProjectInput, type ProjectSpine } from "./spine";

const FANOUT_CONCURRENCY = Math.max(
  1,
  Number(process.env.PROJECT_FANOUT_CONCURRENCY) || 6,
);
const SECTION_TIMEOUT_MS = 4 * 60 * 1000;

const SPECIAL_CHAR_RULES = `SPECIAL CHARACTER RULES (the PDF renderer requires these — follow them exactly):
- Chemical subscripts: CO<sub>2</sub>, H<sub>2</sub>O — use HTML sub tags. Ion charges/exponents: Ca<sup>2+</sup>, x<sup>2</sup> — use HTML sup tags.
- NEVER use Unicode subscripts/superscripts, Greek letters (spell them: alpha, beta, pi), arrows (use ->, <-), or math symbols (use >=, <=, sqrt, !=).`;

/** Identifying details live on the separately-rendered cover page only — never in the body. */
const IDENTITY_RULE = `Do NOT write the student's name, school name, centre number or candidate number anywhere in the body — those appear on a separately generated cover page.`;

function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

/** Run tasks with bounded concurrency; returns result promises in input order. */
function runPool<T, R>(items: T[], limit: number, fn: (item: T, i: number) => Promise<R>): Promise<R>[] {
  let active = 0;
  const waiters: (() => void)[] = [];
  const acquire = () =>
    new Promise<void>((resolve) => {
      if (active < limit) { active++; resolve(); }
      else waiters.push(() => { active++; resolve(); });
    });
  const release = () => {
    active--;
    waiters.shift()?.();
  };
  return items.map((item, i) => acquire().then(() => fn(item, i)).finally(release));
}

function buildSectionPrompt(input: ProjectInput, spine: ProjectSpine, unit: SectionUnit): string {
  const pronoun = input.isGroupProject ? "We" : "I";
  const voice = `${PROJECT_VOICE}${isALevel(input.grade) ? `\n${PROJECT_VOICE_ALEVEL}` : ""}`;
  return `You are writing ONE part of a ${input.grade} ZIMSEC ${input.subject} project: "${spine.title}".

${renderSpineContext(spine)}

${voice}

WRITE ONLY THE SECTION(S) BELOW. Output the markdown starting exactly at the heading shown. Do NOT write the project title (no top-level "# " heading), do NOT write an introduction or any other stage, and do NOT repeat content from other stages. Write in the first person as "${pronoun}", in formal British English, with specific Zimbabwean detail. Every table MUST have a header row separated by |---|---|. Hit the stated word counts.

${unit.guide}

${IDENTITY_RULE}

${SPECIAL_CHAR_RULES}`;
}

async function generateSection(input: ProjectInput, spine: ProjectSpine, unit: SectionUnit): Promise<string> {
  const drain = async (): Promise<string> => {
    const result = await projectAgent.stream(buildSectionPrompt(input, spine, unit), {
      abortSignal: AbortSignal.timeout(SECTION_TIMEOUT_MS),
    });
    let text = "";
    for await (const chunk of result.textStream) text += chunk;
    return text.trim();
  };

  let text = await withRetry(drain);

  // Cheap per-unit top-up: if a unit came back well short, ask once more.
  // Replaces the old whole-document expansion pass (which re-ran everything).
  if (unit.targetWords > 0 && countWords(text) < unit.targetWords * 0.7) {
    try {
      const topUp = await withRetry(async () => {
        const result = await projectAgent.stream(
          `${buildSectionPrompt(input, spine, unit)}\n\nYour previous draft was too short. Rewrite this section in full, longer and more detailed, reaching the stated word counts. Return the COMPLETE section:\n\n${text}`,
          { abortSignal: AbortSignal.timeout(SECTION_TIMEOUT_MS) },
        );
        let t = "";
        for await (const chunk of result.textStream) t += chunk;
        return t.trim();
      });
      if (countWords(topUp) > countWords(text)) text = topUp;
    } catch {
      // Keep the original draft if the top-up fails.
    }
  }
  return text;
}

export type GenerateResult = { title: string; content: string };

/**
 * Generate a full project in parallel.
 * `onSection` (optional) is called in document order as each part is ready —
 * used by the web SSE endpoint to stream progressively.
 */
export async function generateProjectContent(
  input: ProjectInput,
  opts: { onSection?: (markdown: string) => void | Promise<void> } = {},
): Promise<GenerateResult> {
  const { spine, sections } = await withRetry(() => generateSpine(input));
  const units = sections && sections.length > 0 ? sections : buildSectionUnits(input.grade);

  // Start every section concurrently (bounded), then assemble in order.
  const promises = runPool(units, FANOUT_CONCURRENCY, (unit) => generateSection(input, spine, unit));

  const header = `# ${spine.title}\n\n`;
  await opts.onSection?.(header);
  const parts: string[] = [header.trim()];

  for (let i = 0; i < promises.length; i++) {
    const sectionText = await promises[i]!;
    await opts.onSection?.(`${sectionText}\n\n`);
    parts.push(sectionText);
  }

  return { title: spine.title, content: parts.join("\n\n").trim() };
}
