/**
 * Unified ZIMSEC HBC 6-stage project structure, partitioned into independently
 * generatable SECTION UNITS for parallel fan-out generation.
 *
 * This is the single source of truth for the project structure used by BOTH the
 * web controller and the WhatsApp flow (previously duplicated, and drifted to
 * 5-stage vs 6-stage). The authoritative structure is the 6-stage one.
 *
 * Each unit is generated by its own concurrent model call (see generate.ts) and
 * the results are concatenated in `order`. Word ranges scale by grade; the
 * qualitative instructions (tables, "full paragraphs", "named Zimbabwean
 * detail") are preserved from the original prompts.
 */

type Range = [number, number];

const w = (r: Range): string => `${r[0]}-${r[1]} words`;
const mid = (r: Range): number => Math.round((r[0] + r[1]) / 2);

/** Per-grade word ranges and counts for every subsection of the 6 stages. */
type GradeSpec = {
  total: number;
  isALevel: boolean;
  s11: Range; s12: Range; s13: Range; specCount: number;
  s2intro: Range; relIdea: Range; relStrength: Range; relWeak: Range; relCompare: Range;
  s3intro: Range; solIdea: Range;
  s41: Range; s42: Range; s43: Range; s44: Range; s45: Range;
  s51: Range; s52: Range; s52tables: number; s53: Range;
  s61: Range; s62: Range; s63: Range; recCount: number;
  refs: Range;
};

const GRADE7: GradeSpec = {
  total: 3000, isALevel: false,
  s11: [200, 270], s12: [160, 220], s13: [160, 220], specCount: 3,
  s2intro: [60, 80], relIdea: [130, 180], relStrength: [80, 110], relWeak: [80, 110], relCompare: [120, 170],
  s3intro: [60, 80], solIdea: [130, 180],
  s41: [60, 80], s42: [180, 250], s43: [320, 430], s44: [380, 520], s45: [220, 300],
  s51: [280, 380], s52: [420, 560], s52tables: 2, s53: [160, 220],
  s61: [160, 220], s62: [160, 210], s63: [220, 290], recCount: 4,
  refs: [6, 8],
};

const FORM4: GradeSpec = {
  total: 4500, isALevel: false,
  s11: [240, 330], s12: [200, 270], s13: [200, 270], specCount: 3,
  s2intro: [80, 100], relIdea: [180, 250], relStrength: [120, 160], relWeak: [120, 160], relCompare: [150, 200],
  s3intro: [80, 100], solIdea: [180, 250],
  s41: [70, 90], s42: [240, 320], s43: [440, 600], s44: [540, 720], s45: [380, 510],
  s51: [320, 430], s52: [860, 1150], s52tables: 3, s53: [240, 320],
  s61: [210, 280], s62: [190, 250], s63: [320, 420], recCount: 4,
  refs: [8, 12],
};

const FORM6: GradeSpec = {
  total: 7000, isALevel: true,
  s11: [340, 460], s12: [260, 360], s13: [260, 360], specCount: 4,
  s2intro: [100, 140], relIdea: [220, 300], relStrength: [140, 190], relWeak: [140, 190], relCompare: [200, 280],
  s3intro: [100, 130], solIdea: [220, 300],
  s41: [80, 110], s42: [300, 420], s43: [600, 820], s44: [860, 1100], s45: [540, 720],
  s51: [420, 580], s52: [1400, 1860], s52tables: 4, s53: [360, 480],
  s61: [280, 380], s62: [240, 320], s63: [480, 640], recCount: 6,
  refs: [10, 14],
};

export function isGrade7(grade: string): boolean {
  return /grade\s*7/i.test(grade);
}

export function isALevel(grade: string): boolean {
  return /form\s*6|a.?level/i.test(grade);
}

export function gradeSpec(grade: string): GradeSpec {
  if (isGrade7(grade)) return GRADE7;
  if (isALevel(grade)) return FORM6;
  return FORM4;
}

export function getTargetWords(grade: string): number {
  return gradeSpec(grade).total;
}

/** A single independently-generatable unit of the project. */
export type SectionUnit = {
  id: string;
  /** Human label, used in logs and progress messages. */
  label: string;
  /** Markdown structure + per-subsection instructions for this unit only. */
  guide: string;
  /** Approximate target word count — used for the per-unit top-up safety check. */
  targetWords: number;
};

/**
 * Build the canonical 6-stage section units for a grade.
 * Used when the student did NOT supply their own outline.
 */
export function buildSectionUnits(grade: string): SectionUnit[] {
  const g = gradeSpec(grade);
  const ideaBlock = (n: number) => `### Related Idea ${n}: [Descriptive name]
[Evidence of this existing idea — ${w(g.relIdea)}. Describe it with specific Zimbabwean references where applicable.${g.isALevel ? " Cite named Zimbabwean researchers or institutions where realistic." : ""}]
**Strengths/Advantages:** [2-3 specific strengths, analytically explained — ${w(g.relStrength)}]
**Weaknesses/Limitations:** [2-3 specific weaknesses, analytically explained — ${w(g.relWeak)}]`;

  const solBlock = (n: number) => `### Possible Solution ${n}: [Descriptive name]
[Detailed description — ${w(g.solIdea)}${g.isALevel ? ". Explain how this idea emerged from your Stage 2 analysis" : ""}]
**Advantages:** [2-3 advantages, each explained]
**Disadvantages:** [2-3 disadvantages, each explained]`;

  return [
    {
      id: "stage1",
      label: "Stage 1: Problem Identification",
      targetWords: mid(g.s11) + mid(g.s12) + mid(g.s13),
      guide: `## Stage 1: Problem Identification

### 1.1 Problem Description
[Describe the specific problem, innovation or identified gap — ${w(g.s11)}. Name the specific Zimbabwean community, context and stakeholders affected. Be concrete, not abstract.]

### 1.2 Statement of Intent
[Clear statement of how you intend to address the problem — ${w(g.s12)}. State your goal, your target beneficiaries in your community, and what a successful outcome will look like in concrete terms.]

### 1.3 Design Specifications / Project Parameters
[At least ${g.specCount} measurable specifications — ${w(g.s13)}.
| Specification | Measurable Criterion | Justification |
|---|---|---|
]`,
    },
    {
      id: "stage2",
      label: "Stage 2: Investigation of Related Ideas",
      targetWords: mid(g.s2intro) + 3 * (mid(g.relIdea) + mid(g.relStrength) + mid(g.relWeak)) + mid(g.relCompare),
      guide: `## Stage 2: Investigation of Related Ideas

[Introduction — ${w(g.s2intro)}. Explain how you conducted this investigation and why these three ideas were selected.]

${ideaBlock(1)}

${ideaBlock(2)}

${ideaBlock(3)}

### Comparative Summary
[Analytical comparison — ${w(g.relCompare)}.
| Idea | Key Strength | Key Weakness | Applicability to This Project |
|---|---|---|---|
]`,
    },
    {
      id: "stage3",
      label: "Stage 3: Generation of Possible Solutions",
      targetWords: mid(g.s3intro) + 3 * mid(g.solIdea),
      guide: `## Stage 3: Generation of Ideas / Possible Solutions

[Introduction — ${w(g.s3intro)}. Explain how Stage 2 research informed your original ideas.]

${solBlock(1)}

${solBlock(2)}

${solBlock(3)}

### Solution Comparison Table
| Solution | Core Innovation | Feasibility | Resource Requirements | Expected Impact |
|---|---|---|---|---|`,
    },
    {
      id: "stage4",
      label: "Stage 4: Development and Refinement",
      targetWords: mid(g.s41) + mid(g.s42) + mid(g.s43) + mid(g.s44) + mid(g.s45),
      guide: `## Stage 4: Development / Refinement of Chosen Idea

### 4.1 Chosen Solution
[State which solution was chosen — ${w(g.s41)}.]

### 4.2 Justification of Choice
[At least 2 full-paragraph reasons — ${w(g.s42)}. Reference the Stage 1 design specifications and Stage 2/3 findings to support your choice.]

### 4.3 Refinements and Developments
[Three specific improvements made to the solution — ${w(g.s43)} total. Label each clearly.]
**Development 1:** [Name and description]
**Development 2:** [Name and description]
**Development 3:** [Name and description]
[Include:
| Aspect | Initial Design | After Refinement | Reason for Change |
|---|---|---|---|
]

### 4.4 Background Research (Literature Review)
[Supporting research — ${w(g.s44)}. Include at least TWO tables of research findings. Reference Zimbabwean institutions, textbooks, community knowledge, and government sources.]

### 4.5 Methodology
[Data collection, materials, steps, ethical considerations — ${w(g.s45)}.
| Research Instrument | Purpose | Respondents/Source |
|---|---|---|
| Materials/Resources | Source | Quantity |
|---|---|---|
]`,
    },
    {
      id: "stage5_solution",
      label: "Stage 5: Final Solution",
      targetWords: mid(g.s51),
      guide: `## Stage 5: Presentation of Final Solution

### 5.1 Final Solution Description
[Full description — ${w(g.s51)}. Demonstrate how it satisfies each specification from Stage 1.]`,
    },
    {
      id: "stage5_data",
      label: "Stage 5.2: Data Presentation and Analysis",
      targetWords: mid(g.s52),
      guide: `### 5.2 Data Presentation and Analysis
[Findings with analysis — ${w(g.s52)}. Use at least ${["", "ONE", "TWO", "THREE", "FOUR"][g.s52tables] ?? "THREE"} tables with header rows. Use ### sub-headings for each distinct finding area.${g.isALevel ? " Demonstrate analytical and evaluative thinking with quantitative observations." : ""}]`,
    },
    {
      id: "stage6",
      label: "Stage 6: Evaluation, Recommendations & References",
      targetWords: mid(g.s53) + mid(g.s61) + mid(g.s62) + mid(g.s63),
      guide: `### 5.3 Quality and Standards
[How the solution meets national and community standards — ${w(g.s53)}]

## Stage 6: Evaluation and Recommendations

### 6.1 Relevance to Statement of Intent
[Self-evaluate against what you set out to do in Stage 1 — ${w(g.s61)}. Use evidence from Stage 5.]

### 6.2 Challenges Encountered
[Describe at least 3 specific challenges — ${w(g.s62)}.
| Challenge | Impact | How Addressed |
|---|---|---|
]

### 6.3 Recommendations
[At least ${g.recCount} specific, evidence-based recommendations, each a full paragraph — ${w(g.s63)}]

## References
[${g.refs[0]}-${g.refs[1]} APA-formatted references: textbooks, ZIMSEC publications, named community interviews, government documents]`,
    },
  ];
}
